spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lxblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.163.com
    username: 13480743727@163.com
    password: dsx123456 # 授权码
  redis:
    host: 192.168.200.138
server:
  port: 8001
logging:
  level:
    com.lx: debug
blog:
  host: http://localhost:${server.port}/